spring.application.name=demo


spring.datasource.url=jdbc:postgresql://dpg-cu2oac5ds78s739cpb20-a.frankfurt-postgres.render.com:5432/centered_db
spring.datasource.username=centered_db_user
spring.datasource.password=XdYRVkgi9C7RobyZSgYxcGvS4KWVfcz5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
